import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { Screen } from '@/shared/ui/Screen';
import { Title, Body, Muted } from '@/shared/ui/Text';
import { Button } from '@/shared/ui/Button';
import { Card } from '@/shared/ui/Card';
import { useTheme } from '@/shared/theme/ThemeProvider';
import { activities, ActivityId, TravelProfile } from '../types/profile';
import { loadLocalProfile, saveLocalProfile } from '../services/profileStorage';
const initial: TravelProfile = { name: '', bio: '', country: '', languages: ['English'], activities: ['coffee'], verified: false, rating: 5 };
export function ProfileScreen() { const { t } = useTranslation(); const { theme } = useTheme(); const [profile,setProfile]=useState(initial); const [saved,setSaved]=useState(false); useEffect(()=>{loadLocalProfile().then(p=>p&&setProfile(p));},[]); const toggle=(id:ActivityId)=>setProfile(p=>({...p,activities:p.activities.includes(id)?p.activities.filter(x=>x!==id):[...p.activities,id]})); const save=async()=>{await saveLocalProfile(profile);setSaved(true);}; const inputStyle=[styles.input,{borderColor:theme.colors.border,color:theme.colors.text,backgroundColor:theme.colors.surface}]; return <Screen><Title>{t('profile.title')}</Title><TextInput placeholder={t('profile.name')} placeholderTextColor={theme.colors.muted} value={profile.name} onChangeText={name=>setProfile(p=>({...p,name}))} style={inputStyle}/><TextInput placeholder={t('profile.bio')} placeholderTextColor={theme.colors.muted} value={profile.bio} onChangeText={bio=>setProfile(p=>({...p,bio}))} style={[inputStyle,styles.bio]} multiline/><TextInput placeholder={t('profile.country')} placeholderTextColor={theme.colors.muted} value={profile.country} onChangeText={country=>setProfile(p=>({...p,country}))} style={inputStyle}/><Card><Body>Activities</Body><View style={styles.grid}>{activities.map(a=>{const selected=profile.activities.includes(a.id);return <Pressable key={a.id} onPress={()=>toggle(a.id)} style={[styles.pill,{backgroundColor:selected?theme.colors.primary:theme.colors.primarySoft}]}><Body style={{color:selected?'#fff':theme.colors.text}}>{a.emoji} {a.label}</Body></Pressable>})}</View></Card><Button title={t('profile.save')} onPress={save}/>{saved&&<Muted>Saved. Supabase sync is ready after env setup.</Muted>}</Screen> }
const styles=StyleSheet.create({input:{borderWidth:1,borderRadius:18,padding:14,fontSize:16},bio:{minHeight:110,textAlignVertical:'top'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},pill:{borderRadius:999,paddingVertical:8,paddingHorizontal:12}});
